theme: minima
title: Litt privatliv
author: LP
email: "[github-brukernavn] krøllalfa posteo punktum net"
markdown: kramdown
twitter_username: littprivatliv
github_username: littprivatliv
description: Personvern, sikkerhet, forbrukerrettigheter, lov og rett og sånt.

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
minima:
  date_format: "%d.%m.%Y"

# kramdown info: https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/
#   https://kramdown.gettalong.org/quickref.html
# https://help.github.com/categories/customizing-github-pages/
